export type Service={id:string;provider_id:string;name:string;duration:number;price:number;color:string;active:boolean};
export type Client={id:string;provider_id:string;name:string;phone:string;email:string};
export type Booking={id:string;provider_id:string;client_id:string;service_id:string;starts_at:string;ends_at:string;status:string;price:number;notes:string};
export type Payment={id:string;provider_id:string;booking_id:string;amount:number;method:string;paid_at:string};
export type Provider={id:string;name:string;brand?:import('@/components/brand-settings').Brand};
export type Data={services:Service[];clients:Client[];bookings:Booking[];payments:Payment[];providers:Provider[]};
export const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export const dateKey=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
export const clock=(s:string)=>new Date(s).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'});
export const initialData=():Data=>{const day=dateKey(new Date());const at=(t:string)=>`${day}T${t}:00-03:00`;return {providers:[{id:'demo',name:'Studio Essência'}],services:[{id:'s1',provider_id:'demo',name:'Corte e finalização',duration:60,price:120,color:'mint',active:true},{id:'s2',provider_id:'demo',name:'Manicure e pedicure',duration:90,price:85,color:'blue',active:true},{id:'s3',provider_id:'demo',name:'Design de sobrancelhas',duration:30,price:55,color:'purple',active:true},{id:'s4',provider_id:'demo',name:'Hidratação capilar',duration:60,price:150,color:'peach',active:true}],clients:[{id:'c1',provider_id:'demo',name:'Mariana Costa',phone:'+5521999990001',email:'mariana@example.com'},{id:'c2',provider_id:'demo',name:'Beatriz Almeida',phone:'+5521999990002',email:'beatriz@example.com'},{id:'c3',provider_id:'demo',name:'Camila Rodrigues',phone:'+5521999990003',email:''},{id:'c4',provider_id:'demo',name:'Juliana Santos',phone:'+5521999990004',email:''},{id:'c5',provider_id:'demo',name:'Ana Oliveira',phone:'+5521999990005',email:''}],bookings:[{id:'b1',provider_id:'demo',client_id:'c1',service_id:'s1',starts_at:at('09:00'),ends_at:at('10:00'),status:'concluido',price:120,notes:''},{id:'b2',provider_id:'demo',client_id:'c2',service_id:'s2',starts_at:at('10:30'),ends_at:at('12:00'),status:'confirmado',price:85,notes:''},{id:'b3',provider_id:'demo',client_id:'c3',service_id:'s3',starts_at:at('13:00'),ends_at:at('13:30'),status:'confirmado',price:55,notes:''},{id:'b4',provider_id:'demo',client_id:'c4',service_id:'s4',starts_at:at('14:00'),ends_at:at('15:00'),status:'confirmado',price:150,notes:''},{id:'b5',provider_id:'demo',client_id:'c5',service_id:'s1',starts_at:at('16:00'),ends_at:at('17:00'),status:'pendente',price:120,notes:''}],payments:[{id:'p1',provider_id:'demo',booking_id:'b1',amount:120,method:'Pix',paid_at:at('10:00')}]};};
export const normalizePhone=(v:string)=>{const d=v.replace(/\D/g,'');return '+'+(d.length===11?'55'+d:d)};

export function newId(){const a=crypto.getRandomValues(new Uint8Array(16));a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;const h=Array.from(a,b=>b.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
